name: E-Mail Release Notification
on:
    push
    # release:
    #     types: [released]
jobs:
    notify:
        runs-on: ubuntu-latest
        steps:
            - name: Notify about a new release
              uses: daysofwonder/sendgrid-notification-action@v1.3
              env:
                  SENDGRID_API_TOKEN: ${{ secrets.SENDGRID_API_TOKEN }}
                  RECIPIENTS_URL: ${{ secrets.RECIPIENTS_URL }}
                  SENDER_EMAIL: ${{ secrets.SENDER_EMAIL }}
                  DISTRIBUTION_LISTS: ${{ secrets.DISTRIBUTION_LISTS }}
